// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostoGasolina.Infra.Context;

namespace PostoGasolina.Infra.Migrations
{
    [DbContext(typeof(PostoDbContext))]
    [Migration("20220904114532_ColunaCodigoCliente")]
    partial class ColunaCodigoCliente
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PostoGasolina.Business.Models.Abastecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAbastecimento")
                        .HasColumnType("datetime2");

                    b.Property<float>("Litragem")
                        .HasColumnType("real");

                    b.Property<int>("TipoCombustivelId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorLitro")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("VeiculoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipoCombustivelId");

                    b.HasIndex("VeiculoId");

                    b.ToTable("Abastecimentos");
                });

            modelBuilder.Entity("PostoGasolina.Business.Models.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<long>("Codigo")
                        .HasColumnType("BIGINT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("VARCHAR(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(200)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("PostoGasolina.Business.Models.TipoCombustivel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoCombustivel");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Descricao = "Gasolina"
                        },
                        new
                        {
                            Id = 1,
                            Descricao = "Etanol"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "DieselS10"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "DieselS500"
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Flex"
                        });
                });

            modelBuilder.Entity("PostoGasolina.Business.Models.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("VARCHAR(8)");

                    b.Property<int>("TipoCombustivelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("TipoCombustivelId");

                    b.ToTable("Veiculos");
                });

            modelBuilder.Entity("PostoGasolina.Business.Models.Abastecimento", b =>
                {
                    b.HasOne("PostoGasolina.Business.Models.Cliente", "Cliente")
                        .WithMany("Abastecimentos")
                        .HasForeignKey("ClienteId")
                        .IsRequired();

                    b.HasOne("PostoGasolina.Business.Models.TipoCombustivel", "TipoCombustivel")
                        .WithMany()
                        .HasForeignKey("TipoCombustivelId")
                        .IsRequired();

                    b.HasOne("PostoGasolina.Business.Models.Veiculo", "Veiculo")
                        .WithMany("Abastecimentos")
                        .HasForeignKey("VeiculoId")
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoCombustivel");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("PostoGasolina.Business.Models.Veiculo", b =>
                {
                    b.HasOne("PostoGasolina.Business.Models.Cliente", "Cliente")
                        .WithMany("Veiculos")
                        .HasForeignKey("ClienteId")
                        .IsRequired();

                    b.HasOne("PostoGasolina.Business.Models.TipoCombustivel", "TipoCombustivel")
                        .WithMany()
                        .HasForeignKey("TipoCombustivelId")
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("TipoCombustivel");
                });

            modelBuilder.Entity("PostoGasolina.Business.Models.Cliente", b =>
                {
                    b.Navigation("Abastecimentos");

                    b.Navigation("Veiculos");
                });

            modelBuilder.Entity("PostoGasolina.Business.Models.Veiculo", b =>
                {
                    b.Navigation("Abastecimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
